openapi: 3.0.2
info:
  version: 1.0.0
  title: predecessor-api.github.io/openapi
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'https://github.com/predecessor-api/openapi'
  license:
    name: MIT
    url: 'https://github.com/predecessor-api/openapi/blob/main/LICENSE'
  x-logo:
    url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
  description: 'description.md'
servers:
  - url: 'https://backend.production.omeda-aws.com/api/public'
paths:
  '/get-match/{id}':
    $ref: 'paths/get-match/{id}.yaml'
  '/get-matches-since/{epoch}':
    $ref: 'paths/get-matches-since/{epoch}.yaml'
  '/get-matches-by-player/{player_id}':
    $ref: paths/get-matches-by-player/{player_id}.yaml
components:
  securitySchemes: {}
  # NOTE: Predecessor API currently has no Auth requirements in place
  # securitySchemes:
  #   api_key:
  #     type: apiKey
  #     in: header
  #     name: api_key
  #   basic_auth:
  #     type: http
  #     scheme: basic
security: []
