openapi: 3.0.2
info:
  version: 1.0.0
  title: predecessor-api.github.io
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'https://github.com/predecessor-api/predecessor-api.github.io'
  license:
    name: MIT
    url: 'https://github.com/predecessor-api/predecessor-api.github.io/blob/main/LICENSE'
  x-logo:
    url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
  description: 'description.md'
servers:
  - url: 'https://backend.production.omeda-aws.com/api/public'
paths:
  '/get-match/{id}':
    $ref: 'paths/get-match/{id}.yaml'
  '/get-matches-since/{epoch}':
    $ref: 'paths/get-matches-since/{epoch}.yaml'
components:
  securitySchemes: {}
  # securitySchemes:
  #   main_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: 'http://example.com/api/oauth/dialog'
  #         scopes:
  #           'read:users': read users info
  #           'write:users': modify or remove users
  #   api_key:
  #     type: apiKey
  #     in: header
  #     name: api_key
  #   basic_auth:
  #     type: http
  #     scheme: basic
security: []
